export const defaultHomepageConfig = {
  sectionOrder: [
    "hero",
    "stats",
    "features",
    "assessments",
    "memberships",
    "trainers",
    "testimonials",
    "about",
    "cta",
    "contact",
    "footer",
  ],
  sectionVisibility: {
    hero: true,
    stats: true,
    features: true,
    assessments: true,
    memberships: true,
    trainers: true,
    testimonials: true,
    about: true,
    cta: true,
    contact: true,
    footer: true,
  },
  hero: {
    smallHeading: "MORE SWEAT MORE GLORY",
    mainHeading: "TRAIN. TRACK. TRANSFORM.",
    highlightedText: "REACH YOUR PEAK",
    description:
      "The elite athletic sanctuary engineered for real performance. Experience next-generation coaching, real-time biometric analytics, and high-intensity precision training.",
    primaryBtnText: "GET STARTED",
    primaryBtnAction: "/login",
    secondaryBtnText: "EXPLORE PLANS",
    secondaryBtnAction: "#memberships",
    bgImageUrl: "",
    visible: true,
  },
  stats: {
    title: "PROVEN AT SCALE",
    items: [
      { id: "stat_members", label: "Active Members", value: "500+", isDynamic: true, visible: true },
      { id: "stat_trainers", label: "Certified Coaches", value: "15+", isDynamic: true, visible: true },
      { id: "stat_workouts", label: "Workouts Completed", value: "12,000+", isDynamic: true, visible: true },
      { id: "stat_plans", label: "Membership Tiers", value: "4", isDynamic: true, visible: true },
    ],
    visible: true,
  },
  features: {
    title: "BUILT FOR PEAK ATHLETES",
    description: "Every tool you need to shatter plateaus and master your physical potential.",
    items: [
      { id: "feat_1", title: "Precision Member Management", description: "Seamless profile tracking, membership renewals, and real-time attendance.", icon: "Users", visible: true },
      { id: "feat_2", title: "Pro Coaching Console", description: "Certified trainers assigning personalized regimens and tracking day-to-day progress.", icon: "ShieldCheck", visible: true },
      { id: "feat_3", title: "Automated Billing & Invoices", description: "Instant digital receipts across UPI, Card, Cash, with automatic expiry alerts.", icon: "CreditCard", visible: true },
      { id: "feat_4", title: "Real-Time Check-In Hub", description: "Live floor headcount and attendance auditing for maximum safety and accountability.", icon: "CalendarCheck", visible: true },
      { id: "feat_5", title: "Custom Workout Builder", description: "Targeted muscle group exercise library with sets, reps, load, and rest timers.", icon: "Dumbbell", visible: true },
      { id: "feat_6", title: "Body Composition Analytics", description: "Machine PDF integration (InBody / Tanita) with historical metric visualization.", icon: "FileSpreadsheet", visible: true },
    ],
    visible: true,
  },
  assessments: {
    title: "CLINICAL BODY COMPOSITION & BMI",
    description: "Direct integration with Tanita & InBody medical-grade analyzers for absolute transparency in body fat %, muscle mass, and metabolic rate.",
    visible: true,
  },
  memberships: {
    title: "MEMBERSHIP TIERS",
    description: "Transparent, performance-driven investment in your health. No hidden fees.",
    visible: true,
  },
  trainers: {
    title: "MEET OUR ELITE COACHES",
    description: "Master trainers with proven track records in powerlifting, athletic conditioning, and clinical fat loss.",
    selectedTrainerIds: [],
    visible: true,
  },
  testimonials: {
    title: "ATHLETE TRANSFORMATIONS",
    description: "Real words from the dedicated members who put in the sweat every single day.",
    visible: true,
  },
  about: {
    heading: "ABOUT O2 HYPERFIT",
    description: "O2 HyperFit was founded on one unshakeable conviction: generic fitness produces generic results.",
    gymStory: "Our facility pairs Olympic-standard strength apparatus with cutting-edge biometrics, certified elite trainers, and an uncompromising dark athletic atmosphere designed to foster discipline and peak output.",
    imageUrl: "",
    visible: true,
  },
  cta: {
    heading: "READY TO TRANSCEND YOUR LIMITS?",
    description: "Join the O2 HyperFit movement today. Step inside, crush your barriers, and experience the highest standard of fitness.",
    btnText: "START YOUR JOURNEY",
    btnAction: "/login",
    bgImageUrl: "",
    visible: true,
  },
  contact: {
    address: "42, Prime Fitness Boulevard, Metro City, India",
    phone: "+91 98765 43210",
    email: "contact@o2hyperfit.com",
    openingHours: "Mon-Sat: 06:00 AM - 10:00 PM | Sun: Closed",
    mapsUrl: "https://maps.google.com",
    instagramUrl: "https://instagram.com",
    facebookUrl: "https://facebook.com",
    whatsappUrl: "https://whatsapp.com",
    visible: true,
  },
  footer: {
    description: "O2 HyperFit is a premier strength, conditioning, and biometric fitness center engineered for peak athletic performance.",
    copyrightText: "© 2026 O2 HyperFit. All Rights Reserved. Built for champions.",
    visible: true,
  },
};
