"use client";

import React, { useState, useEffect } from "react";
import { AppLayout } from "@/components/layout/AppLayout";
import { useAuth } from "@/context/AuthContext";
import { AssessmentVisualization } from "@/components/assessments/AssessmentVisualization";
import {
  FileSpreadsheet,
  Download,
  Trash2,
  Calendar,
  User,
  Search,
  Loader2,
  FileText,
  Upload,
  ArrowUpRight,
  Sparkles,
  CheckCircle2,
  AlertCircle,
  Clock,
  Filter,
} from "lucide-react";

export default function AssessmentsPage() {
  const { user } = useAuth();
  const [assessments, setAssessments] = useState<any[]>([]);
  const [members, setMembers] = useState<any[]>([]);
  const [selectedMemberId, setSelectedMemberId] = useState<string>("");
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");

  // Member upload form state
  const [uploading, setUploading] = useState(false);
  const [file, setFile] = useState<File | null>(null);
  const [date, setDate] = useState(new Date().toISOString().split("T")[0]);
  const [notes, setNotes] = useState("");
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [successMsg, setSuccessMsg] = useState<string | null>(null);

  const fetchAssessments = async (memberFilter?: string) => {
    try {
      setLoading(true);
      let url = "/api/assessments";
      if (user?.role === "MEMBER") {
        url = "/api/member/body-assessments";
      } else if (memberFilter) {
        url = `/api/admin/members/${memberFilter}/body-assessments`;
      }
      const res = await fetch(url);
      const json = await res.json();
      if (json.success) {
        setAssessments(json.data || []);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const fetchMembers = async () => {
    if (user?.role !== "MEMBER") {
      try {
        const res = await fetch("/api/members");
        const json = await res.json();
        if (json.success) setMembers(json.data);
      } catch (err) {
        console.error(err);
      }
    }
  };

  useEffect(() => {
    fetchAssessments(selectedMemberId);
    fetchMembers();
  }, [selectedMemberId]);

  // Member upload handler
  const handleMemberUpload = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!file) {
      setErrorMsg("Please select a PDF file generated by the BMI / body composition machine.");
      return;
    }

    // Client-side validations
    if (!file.name.toLowerCase().endsWith(".pdf") && file.type !== "application/pdf") {
      setErrorMsg("Invalid file type. Only PDF reports are allowed.");
      return;
    }

    if (file.size > 15 * 1024 * 1024) {
      setErrorMsg("File size exceeds 15MB limit.");
      return;
    }

    setUploading(true);
    setErrorMsg(null);
    setSuccessMsg(null);

    try {
      const formData = new FormData();
      formData.append("file", file);
      formData.append("assessmentDate", date);
      if (notes) formData.append("notes", notes);

      const res = await fetch("/api/member/body-assessments", {
        method: "POST",
        body: formData,
      });

      const json = await res.json();
      if (res.ok && json.success) {
        setSuccessMsg(
          json.message ||
            "Report uploaded successfully! Measurable metrics have been parsed and indexed."
        );
        setFile(null);
        setNotes("");
        // Reset file input element
        const fileInput = document.getElementById("bmi-file-input") as HTMLInputElement;
        if (fileInput) fileInput.value = "";
        fetchAssessments();
      } else {
        setErrorMsg(json.error || "Failed to upload PDF report");
      }
    } catch (err: any) {
      setErrorMsg(err.message || "Failed to upload assessment");
    } finally {
      setUploading(false);
    }
  };

  const handleDelete = async (id: string) => {
    if (!confirm("Are you sure you want to delete this assessment report?")) return;
    try {
      const res = await fetch(`/api/assessments?id=${id}`, { method: "DELETE" });
      if (res.ok) fetchAssessments(selectedMemberId);
    } catch (err) {
      console.error(err);
    }
  };

  const filteredAssessments = assessments.filter((a) => {
    if (!search) return true;
    const term = search.toLowerCase();
    return (
      a.member?.fullName?.toLowerCase().includes(term) ||
      a.member?.memberId?.toLowerCase().includes(term) ||
      a.pdfFileName?.toLowerCase().includes(term) ||
      a.notes?.toLowerCase().includes(term)
    );
  });

  // Sort newest first
  const sortedAssessments = [...filteredAssessments].sort(
    (a, b) => new Date(b.assessmentDate).getTime() - new Date(a.assessmentDate).getTime()
  );

  return (
    <AppLayout
      title="Body Assessments"
      subtitle={
        user?.role === "MEMBER"
          ? "Upload and track your gym body composition and BMI reports"
          : "View-only body analyzer reports and member progress history"
      }
    >
      {/* ========================================================
          1. MEMBER VIEW: UPLOAD FORM + ANALYTICS + REPORT HISTORY
          ======================================================== */}
      {user?.role === "MEMBER" ? (
        <div className="space-y-8">
          {/* Member Upload Card (Requirement 2) */}
          <div className="bg-white rounded-3xl p-6 sm:p-8 border border-slate-200/90 shadow-xs">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-3 bg-brand-500/10 text-brand-600 rounded-2xl">
                <Upload className="h-6 w-6" />
              </div>
              <div>
                <h2 className="text-base font-black uppercase tracking-tight text-slate-900">
                  Upload Body Assessment Report
                </h2>
                <p className="text-xs text-slate-500">
                  Upload the raw PDF scan generated by the gym's BMI machine (InBody, Tanita, Accuniq, etc.)
                </p>
              </div>
            </div>

            {errorMsg && (
              <div className="mb-4 p-3.5 rounded-2xl bg-rose-50 border border-rose-200 text-rose-700 text-xs font-semibold flex items-center gap-2">
                <AlertCircle className="h-4 w-4 shrink-0" />
                <span>{errorMsg}</span>
              </div>
            )}

            {successMsg && (
              <div className="mb-4 p-3.5 rounded-2xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-xs font-semibold flex items-center gap-2">
                <CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-600" />
                <span>{successMsg}</span>
              </div>
            )}

            <form onSubmit={handleMemberUpload} className="space-y-5 text-xs">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block font-bold text-slate-700 uppercase tracking-wider mb-1.5">
                    Assessment Date *
                  </label>
                  <input
                    type="date"
                    required
                    value={date}
                    onChange={(e) => setDate(e.target.value)}
                    className="w-full px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-slate-800 font-semibold focus:outline-hidden focus:ring-2 focus:ring-brand-500"
                  />
                  <p className="text-[11px] text-slate-400 mt-1">Date when the body scan was conducted</p>
                </div>

                <div>
                  <label className="block font-bold text-slate-700 uppercase tracking-wider mb-1.5">
                    Upload Report (PDF only) *
                  </label>
                  <input
                    id="bmi-file-input"
                    type="file"
                    accept=".pdf,application/pdf"
                    required
                    onChange={(e) => setFile(e.target.files?.[0] || null)}
                    className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl file:mr-3 file:py-1 file:px-3 file:rounded-lg file:border-0 file:text-xs file:font-bold file:bg-dark-950 file:text-brand-500 hover:file:bg-dark-900 cursor-pointer"
                  />
                  <p className="text-[11px] text-slate-400 mt-1">Max 15MB. Only authentic analyzer PDF files allowed.</p>
                </div>
              </div>

              <div>
                <label className="block font-bold text-slate-700 uppercase tracking-wider mb-1.5">
                  Notes (Optional)
                </label>
                <textarea
                  rows={2}
                  value={notes}
                  onChange={(e) => setNotes(e.target.value)}
                  placeholder="Optional notes, e.g. Pre-workout morning fasted scan, 4 weeks into cutting cycle..."
                  className="w-full px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-slate-800 placeholder-slate-400 focus:outline-hidden focus:ring-2 focus:ring-brand-500"
                />
              </div>

              <div className="flex justify-end pt-2">
                <button
                  type="submit"
                  disabled={uploading}
                  className="px-6 py-2.5 bg-brand-500 hover:bg-brand-600 text-white rounded-xl font-bold uppercase tracking-wider flex items-center gap-2 shadow-sm transition disabled:opacity-50 cursor-pointer"
                >
                  {uploading ? (
                    <>
                      <Loader2 className="h-4 w-4 animate-spin" />
                      Parsing & Uploading...
                    </>
                  ) : (
                    <>
                      <Upload className="h-4 w-4" />
                      Upload Report
                    </>
                  )}
                </button>
              </div>
            </form>
          </div>

          {/* Assessment Visualizations & Charts (Requirements 4, 5, 6) */}
          {assessments.length > 0 && (
            <AssessmentVisualization assessments={assessments} isAdminView={false} />
          )}

          {/* MY BODY ASSESSMENTS Section (Requirement 3) */}
          <div className="bg-white rounded-3xl p-6 sm:p-8 border border-slate-200/90 shadow-xs">
            <div className="flex items-center justify-between mb-5">
              <div>
                <h3 className="text-base font-black uppercase tracking-tight text-slate-900 flex items-center gap-2">
                  <FileSpreadsheet className="h-4 w-4 text-brand-500" />
                  MY BODY ASSESSMENTS
                </h3>
                <p className="text-xs text-slate-500">
                  Chronological archive of all reports submitted by you ({sortedAssessments.length} total)
                </p>
              </div>
            </div>

            {loading ? (
              <div className="flex h-48 items-center justify-center">
                <Loader2 className="h-6 w-6 text-brand-500 animate-spin" />
              </div>
            ) : sortedAssessments.length === 0 ? (
              <div className="text-center py-12 text-slate-400 text-xs border border-dashed border-slate-200 rounded-2xl">
                <FileText className="h-8 w-8 mx-auto text-slate-300 mb-2" />
                <p className="font-semibold text-slate-600">No assessment reports uploaded yet.</p>
                <p className="text-[11px] text-slate-400 mt-0.5">Use the upload card above to add your first report.</p>
              </div>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {sortedAssessments.map((ass) => (
                  <div
                    key={ass.id}
                    className="p-5 rounded-2xl border border-slate-200/90 bg-slate-50/70 hover:bg-slate-100/60 transition flex flex-col justify-between gap-4"
                  >
                    <div>
                      {/* Top Header */}
                      <div className="flex items-center justify-between gap-2 mb-2">
                        <span className="font-black text-slate-900 text-sm">
                          {new Date(ass.assessmentDate).toLocaleDateString("en-US", {
                            day: "2-digit",
                            month: "short",
                            year: "numeric",
                          })}
                        </span>
                        <span className="px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-emerald-100 text-emerald-700">
                          Processed
                        </span>
                      </div>

                      <h4 className="font-bold text-slate-800 text-xs truncate mb-1">
                        {ass.pdfFileName}
                      </h4>

                      <p className="text-[11px] text-slate-500 mb-3">
                        Uploaded: {new Date(ass.createdAt || ass.assessmentDate).toLocaleDateString("en-US", {
                          day: "2-digit",
                          month: "short",
                          year: "numeric",
                        })}
                      </p>

                      {/* Extracted Metrics Tags */}
                      <div className="flex flex-wrap gap-1.5 mb-3">
                        {ass.weightKg !== null && ass.weightKg !== undefined && (
                          <span className="px-2 py-0.5 rounded-md bg-white border border-slate-200 text-[10px] font-bold text-slate-800">
                            Wt: {ass.weightKg}kg
                          </span>
                        )}
                        {ass.bodyFatPercentage !== null && ass.bodyFatPercentage !== undefined && (
                          <span className="px-2 py-0.5 rounded-md bg-white border border-slate-200 text-[10px] font-bold text-amber-700">
                            Fat: {ass.bodyFatPercentage}%
                          </span>
                        )}
                        {ass.bmi !== null && ass.bmi !== undefined && (
                          <span className="px-2 py-0.5 rounded-md bg-white border border-slate-200 text-[10px] font-bold text-cyan-700">
                            BMI: {ass.bmi}
                          </span>
                        )}
                        {ass.muscleMassKg !== null && ass.muscleMassKg !== undefined && (
                          <span className="px-2 py-0.5 rounded-md bg-white border border-slate-200 text-[10px] font-bold text-emerald-700">
                            SMM: {ass.muscleMassKg}kg
                          </span>
                        )}
                        {ass.visceralFat !== null && ass.visceralFat !== undefined && (
                          <span className="px-2 py-0.5 rounded-md bg-white border border-slate-200 text-[10px] font-bold text-indigo-700">
                            Visceral: {ass.visceralFat}
                          </span>
                        )}
                        {ass.bmrKcal !== null && ass.bmrKcal !== undefined && (
                          <span className="px-2 py-0.5 rounded-md bg-white border border-slate-200 text-[10px] font-bold text-slate-700">
                            BMR: {ass.bmrKcal}kcal
                          </span>
                        )}
                      </div>

                      {ass.notes && (
                        <p className="text-xs text-slate-600 italic bg-white p-2.5 rounded-xl border border-slate-100">
                          {ass.notes}
                        </p>
                      )}
                    </div>

                    {/* Actions */}
                    <div className="pt-3 border-t border-slate-200/80 flex items-center justify-between">
                      <button
                        onClick={() => handleDelete(ass.id)}
                        className="p-1.5 text-slate-400 hover:text-rose-600 hover:bg-rose-50 rounded-lg transition"
                        title="Delete Report"
                      >
                        <Trash2 className="h-4 w-4" />
                      </button>

                      <div className="flex items-center gap-2">
                        <a
                          href={ass.pdfUrl}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="px-3 py-1.5 rounded-xl bg-dark-950 hover:bg-dark-900 text-white text-xs font-bold uppercase tracking-wider flex items-center gap-1 transition shadow-xs"
                        >
                          <ArrowUpRight className="h-3.5 w-3.5 text-brand-500" />
                          View Report
                        </a>
                        <a
                          href={ass.pdfUrl}
                          download
                          className="px-3 py-1.5 rounded-xl bg-brand-500 hover:bg-brand-600 text-white text-xs font-bold uppercase tracking-wider flex items-center gap-1 transition shadow-xs"
                        >
                          <Download className="h-3.5 w-3.5" />
                          Download
                        </a>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      ) : (
        /* ========================================================
           2. ADMIN / TRAINER VIEW: VIEW-ONLY + MEMBER SELECTOR
           ======================================================== */
        <div className="space-y-6">
          {/* Member Selection & Search Header */}
          <div className="bg-white p-5 rounded-3xl border border-slate-200/90 shadow-xs flex flex-col md:flex-row gap-4 items-center justify-between">
            <div className="flex flex-col sm:flex-row items-center gap-3 w-full md:w-auto">
              <div className="relative w-full sm:w-64">
                <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
                <input
                  type="text"
                  placeholder="Search member, notes, file..."
                  value={search}
                  onChange={(e) => setSearch(e.target.value)}
                  className="w-full pl-10 pr-4 py-2 bg-slate-50 border border-slate-200 rounded-xl text-xs text-slate-800 placeholder-slate-400 focus:outline-hidden focus:ring-2 focus:ring-brand-500"
                />
              </div>

              {/* Member Selector Filter */}
              <div className="relative w-full sm:w-64">
                <select
                  value={selectedMemberId}
                  onChange={(e) => setSelectedMemberId(e.target.value)}
                  className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-xs text-slate-800 font-semibold focus:outline-hidden focus:ring-2 focus:ring-brand-500"
                >
                  <option value="">-- All Member Scans --</option>
                  {members.map((m) => (
                    <option key={m.id} value={m.id}>
                      {m.fullName} ({m.memberId})
                    </option>
                  ))}
                </select>
              </div>
            </div>

            <div className="text-xs text-slate-500 font-medium">
              <span className="px-2.5 py-1 rounded-lg bg-dark-950 text-white font-bold text-[10px] uppercase tracking-wider mr-2">
                View Only
              </span>
              Showing {sortedAssessments.length} reports
            </div>
          </div>

          {/* If a specific member is selected, show their full Progress & Timeline visualizations */}
          {selectedMemberId && assessments.length > 0 && (
            <AssessmentVisualization assessments={assessments} isAdminView={true} />
          )}

          {/* Admin Reports Grid */}
          {loading ? (
            <div className="flex h-96 items-center justify-center">
              <Loader2 className="h-8 w-8 text-brand-500 animate-spin" />
            </div>
          ) : sortedAssessments.length === 0 ? (
            <div className="bg-white p-12 rounded-3xl border border-slate-200/90 text-center text-slate-400">
              <FileSpreadsheet className="h-10 w-10 mx-auto text-slate-300 mb-2" />
              <p className="font-bold text-sm text-slate-700">No assessment reports found</p>
              <p className="text-xs text-slate-400 mt-1">
                Members upload their body composition reports directly through their member dashboard.
              </p>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
              {sortedAssessments.map((ass) => (
                <div
                  key={ass.id}
                  className="bg-white rounded-3xl p-5 border border-slate-200/90 shadow-xs hover:shadow-md transition flex flex-col justify-between"
                >
                  <div>
                    <div className="flex items-start justify-between mb-3">
                      <div className="p-3 bg-brand-50 text-brand-600 rounded-2xl">
                        <FileText className="h-6 w-6" />
                      </div>
                      <button
                        onClick={() => handleDelete(ass.id)}
                        className="p-1.5 text-slate-400 hover:text-rose-600 hover:bg-rose-50 rounded-lg transition"
                        title="Delete Report"
                      >
                        <Trash2 className="h-4 w-4" />
                      </button>
                    </div>

                    <h3 className="font-black text-slate-900 text-sm mb-0.5">
                      {ass.member?.fullName}
                    </h3>
                    <p className="font-mono text-xs text-brand-600 font-bold mb-3">
                      {ass.member?.memberId}
                    </p>

                    <div className="space-y-1.5 text-xs text-slate-500 mb-3">
                      <p className="flex items-center gap-1.5">
                        <Calendar className="h-3.5 w-3.5 text-slate-400" />
                        Scan Date: {new Date(ass.assessmentDate).toLocaleDateString()}
                      </p>
                      <p className="truncate text-slate-600 font-medium">
                        File: {ass.pdfFileName}
                      </p>
                    </div>

                    {/* Extracted Metrics Badges */}
                    <div className="flex flex-wrap gap-1.5 mb-3">
                      {ass.weightKg !== null && ass.weightKg !== undefined && (
                        <span className="px-2 py-0.5 rounded-md bg-slate-100 text-[10px] font-bold text-slate-800">
                          {ass.weightKg} kg
                        </span>
                      )}
                      {ass.bodyFatPercentage !== null && ass.bodyFatPercentage !== undefined && (
                        <span className="px-2 py-0.5 rounded-md bg-amber-50 text-[10px] font-bold text-amber-700">
                          {ass.bodyFatPercentage}% Fat
                        </span>
                      )}
                      {ass.bmi !== null && ass.bmi !== undefined && (
                        <span className="px-2 py-0.5 rounded-md bg-cyan-50 text-[10px] font-bold text-cyan-700">
                          BMI {ass.bmi}
                        </span>
                      )}
                      {ass.muscleMassKg !== null && ass.muscleMassKg !== undefined && (
                        <span className="px-2 py-0.5 rounded-md bg-emerald-50 text-[10px] font-bold text-emerald-700">
                          {ass.muscleMassKg} kg SMM
                        </span>
                      )}
                    </div>

                    {ass.notes && (
                      <p className="text-xs text-slate-600 bg-slate-50 p-2.5 rounded-xl border border-slate-100 mb-4 italic">
                        {ass.notes}
                      </p>
                    )}
                  </div>

                  <div className="pt-3 border-t border-slate-100 flex items-center justify-between">
                    <span className="text-[11px] text-slate-400">
                      Uploaded by {ass.uploadedBy?.name || ass.member?.fullName || "Member"}
                    </span>
                    <div className="flex items-center gap-1.5">
                      <a
                        href={ass.pdfUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="px-3 py-1.5 rounded-xl bg-dark-950 hover:bg-dark-900 text-white font-bold text-xs flex items-center gap-1 transition shadow-xs"
                      >
                        <ArrowUpRight className="h-3.5 w-3.5 text-brand-500" />
                        View
                      </a>
                      <a
                        href={ass.pdfUrl}
                        download
                        className="px-3 py-1.5 rounded-xl bg-brand-500 hover:bg-brand-600 text-white font-bold text-xs flex items-center gap-1 transition shadow-xs"
                      >
                        <Download className="h-3.5 w-3.5" />
                        PDF
                      </a>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}
    </AppLayout>
  );
}
