export const dynamic = "force-dynamic";
import { NextRequest, NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { requireAuth } from "@/lib/auth";
import { getStorageService } from "@/lib/storage";
import { parseAssessmentPdf } from "@/lib/pdfParser";
import { Role } from "@prisma/client";

// Max file size: 15MB
const MAX_FILE_SIZE = 15 * 1024 * 1024;

/**
 * GET /api/member/body-assessments
 * Returns all body assessments for the authenticated member, sorted newest first.
 */
export async function GET(req: NextRequest) {
  const auth = await requireAuth(req);
  if (auth instanceof NextResponse) return auth;

  try {
    // Find member record for current user
    const member = await prisma.member.findFirst({
      where: { userId: auth.user.userId },
    });

    if (!member) {
      return NextResponse.json(
        { success: false, error: "Member profile not found for this account" },
        { status: 404 }
      );
    }

    const assessments = await prisma.bodyAssessment.findMany({
      where: { memberId: member.id },
      orderBy: { assessmentDate: "desc" },
    });

    return NextResponse.json({
      success: true,
      data: assessments,
    });
  } catch (error) {
    console.error("GET /api/member/body-assessments error:", error);
    return NextResponse.json(
      { success: false, error: "Failed to fetch member body assessments" },
      { status: 500 }
    );
  }
}

/**
 * POST /api/member/body-assessments
 * Allows an authenticated member to upload their own BMI / body composition report.
 * Parses PDF metrics reliably without fabrication and archives the file.
 */
export async function POST(req: NextRequest) {
  const auth = await requireAuth(req);
  if (auth instanceof NextResponse) return auth;

  // Explicit check: Admins cannot upload reports
  if (auth.user.role === Role.ADMIN) {
    return NextResponse.json(
      {
        success: false,
        error: "Admins are not permitted to upload BMI reports on behalf of members.",
      },
      { status: 403 }
    );
  }

  try {
    // Verify member exists for current user
    const member = await prisma.member.findFirst({
      where: { userId: auth.user.userId },
    });

    if (!member) {
      return NextResponse.json(
        { success: false, error: "Member profile not found for this account." },
        { status: 404 }
      );
    }

    const formData = await req.formData();
    const file = formData.get("file") as File | null;
    const assessmentDateInput = formData.get("assessmentDate") as string | null;
    const notes = formData.get("notes") as string | null;

    if (!file) {
      return NextResponse.json(
        { success: false, error: "A PDF report file is required." },
        { status: 400 }
      );
    }

    // 1. Validate file size
    if (file.size > MAX_FILE_SIZE) {
      return NextResponse.json(
        {
          success: false,
          error: `File size exceeds the 15MB limit. Please upload a smaller file.`,
        },
        { status: 400 }
      );
    }

    // 2. Validate MIME type & file extension
    const hasPdfExtension = file.name.toLowerCase().endsWith(".pdf");
    const hasPdfMime = file.type === "application/pdf" || file.type === "application/x-pdf";
    if (!hasPdfExtension && !hasPdfMime) {
      return NextResponse.json(
        {
          success: false,
          error: "Invalid file type. Only PDF reports generated by body composition analyzers are supported.",
        },
        { status: 400 }
      );
    }

    // Read buffer
    const arrayBuffer = await file.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);

    // 3. Validate magic bytes (%PDF)
    const magicHeader = buffer.slice(0, 5).toString("ascii");
    if (!magicHeader.startsWith("%PDF")) {
      return NextResponse.json(
        {
          success: false,
          error: "The uploaded file is not a valid PDF document.",
        },
        { status: 400 }
      );
    }

    // 4. Validate assessment date
    let assessmentDate = new Date();
    if (assessmentDateInput) {
      const parsedDate = new Date(assessmentDateInput);
      if (!isNaN(parsedDate.getTime())) {
        assessmentDate = parsedDate;
      }
    }

    // 5. Parse verifiable metrics from PDF
    const extracted = await parseAssessmentPdf(buffer);

    // 6. Save PDF using storage service abstraction
    const storageService = getStorageService();
    const uploadResult = await storageService.uploadFile(
      buffer,
      file.name,
      "application/pdf",
      "assessments"
    );

    // 7. Store in database
    const assessment = await prisma.bodyAssessment.create({
      data: {
        memberId: member.id,
        assessmentDate,
        pdfFileName: file.name,
        pdfPath: uploadResult.path,
        pdfUrl: uploadResult.url,
        notes: notes ? notes.trim() : null,
        uploadedById: auth.user.userId,
        weightKg: extracted.weightKg,
        bmi: extracted.bmi,
        bodyFatPercentage: extracted.bodyFatPercentage,
        muscleMassKg: extracted.muscleMassKg,
        bodyWaterPercentage: extracted.bodyWaterPercentage,
        visceralFat: extracted.visceralFat,
        boneMassKg: extracted.boneMassKg,
        bmrKcal: extracted.bmrKcal,
        bodyAge: extracted.bodyAge,
        skeletalMusclePercentage: extracted.skeletalMusclePercentage,
        metrics: extracted.metrics,
      },
    });

    return NextResponse.json(
      {
        success: true,
        message: "Body assessment report uploaded and processed successfully",
        data: assessment,
        extractedMetrics: extracted.metrics,
      },
      { status: 201 }
    );
  } catch (error) {
    console.error("POST /api/member/body-assessments error:", error);
    return NextResponse.json(
      { success: false, error: "Failed to upload and process body assessment PDF." },
      { status: 500 }
    );
  }
}
